# SPDX-License-Identifier: FSL-1.1-ALv2
# Copyright 2026 Alexander Atkins
# Licensed under the Functional Source License, Version 1.1, ALv2 Future License.
# Each version becomes Apache-2.0 two years after its release. See LICENSE.

"""
SpacyBackend — local NLP enrichment using spaCy.

This backend runs entirely in-process.  It requires the ``en_core_web_sm``
model (``python -m spacy download en_core_web_sm``) and does not make any
network calls.

Characteristics
---------------
- **Speed:** Very fast for short documents; scales linearly with body length.
- **Quality:** Good for entity extraction and keyword frequency.  Topic
  extraction is coarse (noun-chunk roots only).  Summary is generated by
  extractive selection, not abstraction.
- **Resource usage:** CPU-bound.  The spaCy model is loaded once and cached
  for the process lifetime (``@lru_cache``).
- **Concurrency:** Run via ``asyncio.to_thread`` — does not block the event
  loop.

Prompt handling
---------------
Unlike LLM backends, ``SpacyBackend`` does not interpret the prompt string.
The prompt is passed for interface conformance; actual document content is
passed separately via the constructor or extracted from the structured prompt
header.  In practice, callers pass the raw ``(title, body)`` pair through
``build_extraction_prompt`` and this backend extracts the content section.

However, for simplicity and to keep the interface clean, this backend
**accepts the prompt as a convenience hint only** — it operates on the
``title`` and ``body`` passed at call time through the session context.
The ``MetadataProcessor`` passes the original document to this backend
directly when it falls back from a failed LLM call.

Implementation note
--------------------
``complete()`` is defined to accept and ignore the prompt string, then runs
NLP on the stored document text.  The processor sets ``_current_doc`` before
calling ``complete()``.  This is intentional: it avoids re-parsing the
document from the prompt string (which would be lossy) while keeping the
Protocol interface consistent.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from functools import lru_cache

import spacy
from spacy.language import Language

from dewie.enrichment.base import BackendError, ExtractionResult

logger = logging.getLogger(__name__)

# ── NER labels to retain ─────────────────────────────────────────────────────

_ENTITY_LABELS = frozenset({"ORG", "PERSON", "GPE", "PRODUCT", "EVENT", "WORK_OF_ART", "LAW"})

# ── Minimal sentiment lexicon (extend or replace with a proper classifier) ───

_POS_WORDS = frozenset(
    ["good", "great", "excellent", "positive", "amazing", "innovative", "success", "growth"]
)
_NEG_WORDS = frozenset(
    ["bad", "terrible", "negative", "failure", "crisis", "decline", "poor", "risk"]
)


@lru_cache(maxsize=1)
def _load_model() -> Language:
    """
    Load the spaCy model once and cache it for the process lifetime.

    Falls back to a blank English model if ``en_core_web_sm`` is not installed,
    so the application starts without NER / POS tagging rather than crashing.
    """
    try:
        return spacy.load("en_core_web_sm")
    except OSError:
        logger.warning(
            "en_core_web_sm not found; falling back to blank model.  "
            "Install with: python -m spacy download en_core_web_sm"
        )
        return spacy.blank("en")


class SpacyBackend:
    """
    Enrichment backend powered by local spaCy NLP.

    This is the default backend — it requires no network access, no API key,
    and no GPU.  It is appropriate for high-volume/low-value content or as a
    fallback when LLM backends are unavailable.

    Usage
    -----
    ::

        backend = SpacyBackend(max_keywords=15, max_topics=8)
        result_json = await backend.complete_with_content(title, body)

    For Protocol-conformant usage (via ``MetadataProcessor``):
    ::

        backend._set_document(title, body)
        result_json = await backend.complete(prompt)
    """

    def __init__(
        self,
        max_keywords: int = 15,
        max_topics: int = 8,
        max_entities: int = 20,
    ) -> None:
        """
        Initialise the SpacyBackend.

        Args:
            max_keywords: Maximum number of keywords to extract (TF-IDF heuristic).
            max_topics:   Maximum number of topic labels to extract (noun-chunk frequency).
            max_entities: Maximum number of named entities to return.
        """
        self._max_keywords = max_keywords
        self._max_topics = max_topics
        self._max_entities = max_entities
        # Set by MetadataProcessor before calling complete()
        self._title: str = ""
        self._body: str = ""

    @property
    def name(self) -> str:
        """Backend identifier used in the registry and routing rules."""
        return "spacy"

    def _set_document(self, title: str, body: str) -> None:
        """
        Provide document content before calling ``complete()``.

        The ``MetadataProcessor`` calls this before every ``complete()``
        invocation so the backend operates on the correct document.

        Args:
            title: Document title.
            body:  Document body (full text; not pre-truncated for this backend).
        """
        self._title = title
        self._body = body

    async def complete(self, prompt: str) -> str:  # noqa: ARG002
        """
        Run spaCy NLP on the stored document and return a JSON string.

        The ``prompt`` parameter is accepted for Protocol conformance but is
        not used.  Call ``_set_document(title, body)`` before this method.

        Args:
            prompt: Ignored.  Present for ``EnrichmentBackend`` Protocol conformance.

        Returns:
            JSON string matching ``ExtractionResult`` schema.

        Raises:
            BackendError: If spaCy processing fails.
        """
        try:
            result = await asyncio.to_thread(self._run_nlp, self._title, self._body)
            return json.dumps(result)
        except Exception as exc:
            raise BackendError(f"SpacyBackend NLP failed: {exc}") from exc

    async def complete_with_content(self, title: str, body: str) -> str:
        """
        Convenience method: set document content and run extraction in one call.

        Equivalent to ``_set_document(title, body)`` followed by
        ``await complete("")``.

        Args:
            title: Document title.
            body:  Document body text.

        Returns:
            JSON string matching ``ExtractionResult`` schema.

        Raises:
            BackendError: If spaCy processing fails.
        """
        self._set_document(title, body)
        return await self.complete("")

    # ── Private NLP pipeline (runs in thread pool) ───────────────────────────

    def _run_nlp(self, title: str, body: str) -> dict:  # type: ignore[type-arg]
        """Execute the full spaCy pipeline synchronously (called via to_thread)."""
        text = f"{title}. {body}" if title else body
        nlp = _load_model()
        spacy_doc = nlp(text[:100_000])  # hard cap for safety

        entities = _extract_entities(spacy_doc, self._max_entities)
        keywords = _extract_keywords(text, nlp, self._max_keywords)
        topics = _extract_topics(spacy_doc, self._max_topics)
        sentiment = _compute_sentiment(spacy_doc)
        summary = _extract_summary(body)

        return ExtractionResult(
            document_type=None,  # spaCy cannot classify document type
            keywords=keywords,
            themes=topics,  # spaCy topics surfaced as themes (approximate)
            entities=[{"text": e, "label": "UNKNOWN"} for e in entities],
            summary=summary,
            enrichment_quality_score=None,  # spaCy cannot assign a quality score
            sentiment=sentiment,
            tone=None,  # spaCy cannot assign a tone label
            language="en",  # spaCy en model; language detection not performed
        ).model_dump()


# ── Private NLP helpers ───────────────────────────────────────────────────────


def _extract_entities(spacy_doc: spacy.tokens.Doc, max_n: int) -> list[str]:
    """Return deduplicated entity strings filtered by accepted NER labels."""
    seen: set[str] = set()
    result: list[str] = []
    for ent in spacy_doc.ents:
        if ent.label_ in _ENTITY_LABELS:
            key = ent.text.strip().lower()  # case-normalise to prevent duplicates
            display = ent.text.strip()
            if key and key not in seen:
                seen.add(key)
                result.append(display)
                if len(result) >= max_n:
                    break
    return result


def _extract_keywords(text: str, nlp: Language, max_k: int) -> list[str]:
    """
    Extract top-N keywords using lemma frequency over non-stop, alpha tokens.

    This is a simple TF heuristic; replace with TF-IDF over the corpus for
    production-grade keyword extraction.
    """
    doc = nlp(text[:50_000])
    freq: dict[str, int] = {}
    for token in doc:
        if not token.is_stop and not token.is_punct and token.is_alpha and len(token.text) > 2:
            lemma = token.lemma_.lower()
            freq[lemma] = freq.get(lemma, 0) + 1
    return sorted(freq, key=lambda k: freq[k], reverse=True)[:max_k]


def _extract_topics(spacy_doc: spacy.tokens.Doc, max_t: int) -> list[str]:
    """
    Derive coarse topic labels from the most frequent noun chunk roots.

    Noun chunk roots are lemmatised and deduplicated.  Single-character roots
    and stop words are excluded.
    """
    chunk_freq: dict[str, int] = {}
    for chunk in spacy_doc.noun_chunks:
        key = chunk.root.lemma_.lower()
        if len(key) > 2 and not chunk.root.is_stop:
            chunk_freq[key] = chunk_freq.get(key, 0) + 1
    return sorted(chunk_freq, key=lambda k: chunk_freq[k], reverse=True)[:max_t]


def _compute_sentiment(spacy_doc: spacy.tokens.Doc) -> float:
    """
    Return a polarity score in [-1, 1] using a small hand-crafted lexicon.

    This is intentionally simple.  Replace with a fine-tuned classifier
    (textblob, VADER, or a HuggingFace pipeline) for production use.
    """
    tokens = [t.text.lower() for t in spacy_doc if t.is_alpha]
    if not tokens:
        return 0.0
    pos = sum(1 for t in tokens if t in _POS_WORDS)
    neg = sum(1 for t in tokens if t in _NEG_WORDS)
    total = pos + neg
    if total == 0:
        return 0.0
    return round((pos - neg) / total, 4)


def _extract_summary(body: str, max_chars: int = 500) -> str:
    """
    Extract a short summary by selecting the first complete sentence(s)
    up to ``max_chars`` characters.

    This is extractive, not abstractive.  LLM backends produce better
    summaries; this is used as a fallback.
    """
    body = body.strip()
    if not body:
        return ""
    # Split on sentence boundaries (rough heuristic)
    sentences = re.split(r"(?<=[.!?])\s+", body)
    summary = ""
    for sent in sentences:
        candidate = (summary + " " + sent).strip() if summary else sent
        if len(candidate) > max_chars:
            break
        summary = candidate
    return summary or body[:max_chars]
