#!/usr/bin/env bash
# generate-env.sh — generate a .env file with all required secrets
#
# Run this once before `docker compose up`:
#   bash generate-env.sh
#
# If .env already exists, this will NOT overwrite it.
# To regenerate: rm .env && bash generate-env.sh

set -e

ENV_FILE="${1:-.env}"

if [ -f "$ENV_FILE" ]; then
  echo "✋  $ENV_FILE already exists — not overwriting."
  echo "   Delete it and re-run to generate fresh secrets."
  exit 0
fi

# Generate secrets
PG_PASS=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")
JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
ADMIN_KEY=$(python3 -c "import secrets; print('dw_' + secrets.token_urlsafe(24))")
SERVICE_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")

# Read LLM key from user
echo ""
echo "Enter your LLM API key (leave blank to configure later):"
printf "  OPENAI_API_KEY: "; read -r OPENAI_KEY

cat > "$ENV_FILE" <<ENVFILE
# Generated by generate-env.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Keep this file private. Never commit it.

# ── Postgres ──────────────────────────────────────────────────────────────────
POSTGRES_PASSWORD=${PG_PASS}

# ── Auth secrets ──────────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
ADMIN_KEY=${ADMIN_KEY}
INTERNAL_SERVICE_KEY=${SERVICE_KEY}
AUTH_ENABLED=false

# ── LLM provider ──────────────────────────────────────────────────────────────
LLM_PROVIDER=openai
LLM_MODEL=gpt-4o-mini
OPENAI_API_KEY=${OPENAI_KEY}

# ── Embeddings (defaults to same key as LLM) ──────────────────────────────────
EMBED_PROVIDER=openai
EMBED_MODEL=text-embedding-3-small
ENVFILE

echo ""
echo "✅  Written to $ENV_FILE"
echo ""
echo "   POSTGRES_PASSWORD  ${PG_PASS}"
echo "   JWT_SECRET         ${JWT_SECRET:0:16}…"
echo "   ADMIN_KEY          ${ADMIN_KEY}"
echo ""
echo "⚠️  Save these — especially POSTGRES_PASSWORD."
echo "   You will need it if you ever connect to the database directly."
echo ""
echo "Next:"
echo "  docker compose up"
echo "  # Then create your admin account:"
echo "  docker compose exec app dewie admin-user"
