# SPDX-License-Identifier: FSL-1.1-ALv2
# Copyright 2026 Alexander Atkins
# Licensed under the Functional Source License, Version 1.1, ALv2 Future License.
# Each version becomes Apache-2.0 two years after its release. See LICENSE.

"""
dewie — CLI for the Dewie retrieval framework.

Usage:
    dewie serve          # Start the API server
    dewie init           # Initialize config and DB
    dewie ingest <url>   # Ingest a URL or local file
    dewie status         # Show pipeline health

Install:
    pip install dewie
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any


def _require(package: str, install_hint: str = "") -> None:
    """Friendly error if an optional import is missing."""
    try:
        __import__(package)
    except ImportError:
        hint = install_hint or f"pip install {package}"
        print(f"❌  Missing dependency: {package!r}. Install with: {hint}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

try:
    import click
except ImportError:
    print("❌  click is required. Run: pip install dewie", file=sys.stderr)
    sys.exit(1)


@click.group()
@click.version_option(package_name="dewie", prog_name="dewie")
def main() -> None:
    """
    Dewie — agent-native retrieval framework.

    Run `dewie serve` to start, `dewie --help` for all commands.
    """


# ── serve ─────────────────────────────────────────────────────────────────────


@main.command()
@click.option("--host", default="0.0.0.0", show_default=True, help="Bind host.")
@click.option("--port", default=10946, show_default=True, help="Bind port.")
@click.option("--workers", default=1, show_default=True, help="Uvicorn worker count.")
@click.option("--reload", is_flag=True, default=False, help="Enable auto-reload (dev mode).")
@click.option(
    "--config-dir", default=".", show_default=True, help="Directory containing dewie.yml."
)
def serve(host: str, port: int, workers: int, reload: bool, config_dir: str) -> None:
    """Start the Dewie API server on HOST:PORT.

    Config priority (highest to lowest):
      1. Environment variables (POSTGRES_DSN)
      2. dewie.yml (postgres_dsn field)
      3. Default SQLite database (./dewie.db)
    """
    _require("uvicorn", "pip install dewie")
    _require("fastapi", "pip install dewie")

    # Load .env file if present (e.g. from `dewie init` or hand-written).
    # This must happen before _bridge_dewie_yml_to_env so env vars take priority.
    try:
        from dotenv import load_dotenv as _load_dotenv
        _load_dotenv()
    except ImportError:
        pass

    # Bridge secrets and DB URL from dewie.yml into os.environ for the app process.
    # The app reads these directly from os.environ (not Settings), so they must be set here.
    _bridge_dewie_yml_to_env(config_dir)

    import uvicorn  # noqa: PLC0415

    click.echo(f"🚀  Starting Dewie on http://{host}:{port}")
    uvicorn.run(
        "dewie.main:app",
        host=host,
        port=port,
        workers=workers if not reload else 1,
        reload=reload,
        log_level="info",
    )


# ── init ──────────────────────────────────────────────────────────────────────


@main.command()
@click.option("--db-url", default=None, help="Database URL (default: SQLite at ./dewie.db).")
@click.option("--config-dir", default=".", show_default=True, help="Directory to write config.")
def init(db_url: str | None, config_dir: str) -> None:
    """Initialize config file and create DB schema."""
    import textwrap  # noqa: PLC0415

    config_path = os.path.join(config_dir, "dewie.yml")
    resolved_db = db_url or f"sqlite+aiosqlite:///{os.path.abspath('dewie.db')}"

    if not os.path.exists(config_path):
        import secrets as _secrets  # noqa: PLC0415
        generated_admin_key = f"dw_{_secrets.token_urlsafe(24)}"
        generated_jwt_secret = _secrets.token_hex(32)
        generated_service_key = _secrets.token_hex(32)

        config_content = textwrap.dedent(f"""\
            # Dewie configuration
            # Generated by `dewie init`

            postgres_dsn: "{resolved_db}"
            redis_url: ""
            enrichment_default_backend: "passthrough"
            api_host: "0.0.0.0"
            api_port: 10946
            api_workers: 1
            auth_enabled: false
            admin_key: "{generated_admin_key}"
            jwt_secret: "{generated_jwt_secret}"
            internal_service_key: "{generated_service_key}"
        """)
        with open(config_path, "w") as f:
            f.write(config_content)
        click.echo(f"✅  Config written to {config_path}")
        click.echo("")
        click.echo(f"   Admin key:   {generated_admin_key}")
        click.echo(f"   JWT secret:  {generated_jwt_secret[:16]}…  (full value in dewie.yml)")
        click.echo("")
        click.echo("   Save these. Auth is off by default — set auth_enabled: true in dewie.yml for production.")
    else:
        click.echo(f"ℹ️   Config already exists at {config_path} — skipping.")

    os.environ["POSTGRES_DSN"] = resolved_db
    asyncio.run(_init_db(resolved_db))
    click.echo("")
    click.echo("✅  Database ready.")
    click.echo("")
    click.echo("Next steps:")
    click.echo("  dewie admin-user   # create your admin account")
    click.echo("  dewie serve        # start the server")


# ── config ───────────────────────────────────────────────────────────────────


@main.group("config")
def config_group() -> None:
    """Read and write dewie.yml configuration."""


@config_group.command("list")
@click.option(
    "--config-dir", default=".", show_default=True, help="Directory containing dewie.yml."
)
def config_list(config_dir: str) -> None:
    """Print the entire config file as YAML."""
    path = _config_path(config_dir)
    data = _load_config(path)
    _require("yaml", "pip install pyyaml")
    import yaml  # noqa: PLC0415

    click.echo(yaml.safe_dump(data, sort_keys=True).rstrip())


@config_group.command("get")
@click.argument("path")
@click.option(
    "--config-dir", default=".", show_default=True, help="Directory containing dewie.yml."
)
def config_get(path: str, config_dir: str) -> None:
    """Get a single config value by dot-path (e.g. enrichment.mode)."""
    data = _load_config(_config_path(config_dir))
    value = _get_nested(data, path)
    if value is _MISSING:
        raise click.ClickException(f"Config key not found: {path}")
    if isinstance(value, (dict, list)):
        click.echo(json.dumps(value, indent=2))
    else:
        click.echo(value)


@config_group.command("set")
@click.argument("path")
@click.argument("value")
@click.option(
    "--type",
    "value_type",
    type=click.Choice(["auto", "str", "int", "float", "bool", "json"], case_sensitive=False),
    default="auto",
    show_default=True,
    help="Type coercion for VALUE.",
)
@click.option(
    "--config-dir", default=".", show_default=True, help="Directory containing dewie.yml."
)
def config_set(path: str, value: str, value_type: str, config_dir: str) -> None:
    """Set a config value by dot-path (e.g. enrichment.mode dual_pass)."""
    cfg_path = _config_path(config_dir)
    data = _load_config(cfg_path)
    coerced = _coerce_config_value(value, value_type)
    _set_nested(data, path, coerced)
    _save_config(cfg_path, data)
    click.echo(f"✅  Set {path}={coerced!r} in {cfg_path}")


@config_group.command("import")
@click.option("--env-file", default=".env", show_default=True, help="Path to env file.")
@click.option(
    "--config-dir", default=".", show_default=True, help="Directory containing dewie.yml."
)
def config_import(env_file: str, config_dir: str) -> None:
    """Import supported env values from an env file into dewie.yml."""
    cfg_path = _config_path(config_dir)
    data = _load_config(cfg_path)
    imported = _import_env_file(Path(env_file), data)
    _save_config(cfg_path, data)
    click.echo(f"✅  Imported {imported} key(s) from {env_file} into {cfg_path}")


@config_group.command("set-secret")
@click.argument("path")
@click.option(
    "--from-env", "from_env", default=None, help="Read secret from environment variable name."
)
@click.option("--from-file", "from_file", default=None, help="Read secret via file path reference.")
@click.option(
    "--config-dir", default=".", show_default=True, help="Directory containing dewie.yml."
)
def config_set_secret(
    path: str, from_env: str | None, from_file: str | None, config_dir: str
) -> None:
    """Set a secret reference (not raw secret) for a config path."""
    if bool(from_env) == bool(from_file):
        raise click.ClickException("Use exactly one of --from-env or --from-file")

    cfg_path = _config_path(config_dir)
    data = _load_config(cfg_path)

    if from_env:
        _set_nested(data, path, {"secret_ref": {"env": from_env}})
        msg = f"env:{from_env}"
    else:
        _set_nested(data, path, {"secret_ref": {"file": from_file}})
        msg = f"file:{from_file}"

    _save_config(cfg_path, data)
    click.echo(f"✅  Set secret reference for {path} ({msg}) in {cfg_path}")


# ── ingest ────────────────────────────────────────────────────────────────────


@main.command()
@click.argument("source")
@click.option(
    "--api-url", default="http://localhost:10946", show_default=True, help="Dewie API base URL."
)
@click.option(
    "--api-key",
    default=None,
    envvar="DEWIE_API_KEY",
    help="API key (or set DEWIE_API_KEY env var).",
)
@click.option("--source-name", default=None, help="Corpus / source label.")
@click.option("--wait/--no-wait", default=False, help="Wait for enrichment to complete.")
def ingest(
    source: str, api_url: str, api_key: str | None, source_name: str | None, wait: bool
) -> None:
    """
    Ingest a URL or local file path into the Dewie corpus.

    SOURCE can be a URL (https://...) or a local file path.
    """
    _require("httpx", "pip install dewie")
    import httpx  # noqa: PLC0415

    headers: dict[str, str] = {}
    if api_key:
        headers["X-API-Key"] = api_key

    payload: dict[str, object] = {}
    if source.startswith("http://") or source.startswith("https://"):
        payload["url"] = source
    else:
        # Local file — read and POST as body_text
        if not os.path.exists(source):
            click.echo(f"❌  File not found: {source}", err=True)
            sys.exit(1)
        with open(source) as f:
            content = f.read()
        payload["body_text"] = content
        payload["url"] = f"file://{os.path.abspath(source)}"
        payload["title"] = os.path.basename(source)

    if source_name:
        payload["source"] = source_name

    click.echo(f"📥  Ingesting: {source}")
    try:
        with httpx.Client(timeout=30) as client:
            r = client.post(f"{api_url}/api/user/ingest", json=payload, headers=headers)
            r.raise_for_status()
            data = r.json()
    except httpx.HTTPStatusError as e:
        click.echo(f"❌  API error {e.response.status_code}: {e.response.text[:200]}", err=True)
        sys.exit(1)
    except httpx.RequestError as e:
        click.echo(f"❌  Could not reach Dewie at {api_url}: {e}", err=True)
        sys.exit(1)

    doc_id = data.get("doc_id") or data.get("id", "?")
    status = data.get("status", "unknown")
    click.echo(f"✅  Ingested — doc_id: {doc_id}, status: {status}")

    if wait:
        import time  # noqa: PLC0415

        click.echo("⏳  Waiting for enrichment...")
        for _ in range(60):  # max 5 min
            time.sleep(5)
            try:
                with httpx.Client(timeout=10) as client:
                    r = client.get(f"{api_url}/api/documents/{doc_id}", headers=headers)
                    doc = r.json()
                    doc_status = doc.get("status", "unknown")
                    click.echo(f"   status: {doc_status}")
                    if doc_status in ("ready", "failed", "terminal"):
                        break
            except Exception:
                pass
        click.echo(f"✅  Final status: {doc_status}")


# ── setup (interactive wizard) ──────────────────────────────────────────────


@main.command()
@click.option(
    "--config-dir", default=".", show_default=True, help="Directory to write dewie.yml / .env."
)
@click.option("--force", is_flag=True, default=False, help="Re-run even if config already exists.")
@click.option(
    "--compose",
    "compose_mode",
    is_flag=True,
    default=False,
    help="Docker Compose mode: skip storage questions, write .env instead of dewie.yml.",
)
def setup(config_dir: str, force: bool, compose_mode: bool) -> None:
    """
    Interactive first-run setup wizard (arrow-key menus, auto-detects models).

    Use --compose when running with Docker Compose: skips the storage
    step, writes .env, then run `docker compose up`.
    """
    from dewie.setup_wizard import run_setup  # noqa: PLC0415

    run_setup(config_dir=config_dir, force=force, compose_mode=compose_mode)


# ── status ────────────────────────────────────────────────────────────────────


@main.command()
@click.option(
    "--api-url", default="http://localhost:10946", show_default=True, help="Dewie API base URL."
)
@click.option(
    "--api-key",
    default=None,
    envvar="DEWIE_API_KEY",
    help="API key (or set DEWIE_API_KEY env var).",
)
def status(api_url: str, api_key: str | None) -> None:
    """Show Dewie pipeline health: workers, doc counts, enrichment queue."""
    _require("httpx", "pip install dewie")
    import httpx  # noqa: PLC0415

    headers: dict[str, str] = {}
    if api_key:
        headers["X-API-Key"] = api_key

    try:
        with httpx.Client(timeout=10) as client:
            health = client.get(f"{api_url}/health", headers=headers)
            health.raise_for_status()
            h = health.json()
    except Exception as e:
        click.echo(f"❌  Dewie not reachable at {api_url}: {e}", err=True)
        sys.exit(1)

    click.echo(f"\n🟢  Dewie is {'live' if h.get('status') == 'ok' else 'degraded'} at {api_url}\n")

    # Try pipeline worker + error endpoints
    try:
        with httpx.Client(timeout=10) as client:
            workers = client.get(f"{api_url}/pipeline/workers/status", headers=headers)
            errors = client.get(f"{api_url}/pipeline/errors?window=60", headers=headers)

            if workers.status_code == 200:
                w = workers.json()
                click.echo(f"  Workers running: {w.get('running', '?')} / {w.get('total', '?')}")
                click.echo(f"  Workers paused:  {w.get('paused', '?')}")

            if errors.status_code == 200:
                e = errors.json()
                click.echo(f"  Error rate (60m): {e.get('error_rate', '?')}")
                click.echo(f"  Unresolved errs:  {e.get('unresolved_count', '?')}")

            if workers.status_code != 200 and errors.status_code != 200:
                click.echo(f"  API status: {h.get('status', 'unknown')}")
    except Exception:
        click.echo(f"  API status: {h.get('status', 'unknown')}")

    click.echo()


# ── export ────────────────────────────────────────────────────────────────────


@main.command()
@click.option(
    "--corpus",
    "corpus_id",
    required=True,
    help="ID of the corpus to export.",
)
@click.option(
    "--output",
    "output_file",
    required=True,
    type=click.Path(),
    help="Output file path.",
)
@click.option(
    "--format",
    "format",
    default="jsonl",
    type=click.Choice(["jsonl", "json"], case_sensitive=False),
    help="Export format.",
)
@click.option(
    "--api-url", default="http://localhost:10946", show_default=True, help="Dewie API base URL."
)
@click.option(
    "--api-key",
    default=None,
    envvar="DEWIE_API_KEY",
    help="API key (or set DEWIE_API_KEY env var).",
)
def export(
    corpus_id: str, output_file: str, format: str, api_url: str, api_key: str | None
) -> None:
    """Export corpus documents as streaming JSONL or JSON."""
    _require("httpx", "pip install dewie")
    import httpx  # noqa: PLC0415

    headers: dict[str, str] = {}
    if api_key:
        headers["X-API-Key"] = api_key

    params = {"corpus_id": corpus_id, "format": format, "status": "ready"}

    click.echo(f"📤  Exporting corpus {corpus_id} to {output_file} (format={format})")
    try:
        with httpx.stream(
            "GET", f"{api_url}/corpus/export", headers=headers, params=params, timeout=300
        ) as resp:
            if resp.status_code == 404:
                click.echo(f"❌  Corpus not found: {corpus_id}", err=True)
                sys.exit(1)
            if resp.status_code == 403:
                click.echo(f"❌  Access denied to corpus: {corpus_id}", err=True)
                sys.exit(1)
            resp.raise_for_status()
            with open(output_file, "wb") as f:
                for chunk in resp.iter_bytes():
                    f.write(chunk)
    except httpx.HTTPStatusError as e:
        click.echo(f"❌  API error {e.response.status_code}: {e.response.text[:200]}", err=True)
        sys.exit(1)
    except httpx.RequestError as e:
        click.echo(f"❌  Could not reach Dewie at {api_url}: {e}", err=True)
        sys.exit(1)

    click.echo(f"✅  Export complete: {output_file}")


# ── import ────────────────────────────────────────────────────────────────────


@main.command()
@click.option(
    "--input",
    "input_file",
    required=True,
    type=click.Path(exists=True),
    help="Input JSONL/JSON file path.",
)
@click.option(
    "--corpus",
    "corpus_id",
    required=True,
    help="Target corpus ID for import.",
)
@click.option(
    "--api-url", default="http://localhost:10946", show_default=True, help="Dewie API base URL."
)
@click.option(
    "--api-key",
    default=None,
    envvar="DEWIE_API_KEY",
    help="API key (or set DEWIE_API_KEY env var).",
)
@click.option(
    "--skip-duplicates/--upsert-duplicates",
    default=True,
    help="Strategy for handling duplicate document IDs.",
)
def import_cmd(
    input_file: str, corpus_id: str, api_url: str, api_key: str | None, skip_duplicates: bool
) -> None:
    """Import documents from a JSONL/JSON file into a corpus."""
    _require("httpx", "pip install dewie")
    import httpx  # noqa: PLC0415

    headers: dict[str, str] = {"Content-Type": "application/json"}
    if api_key:
        headers["X-API-Key"] = api_key

    click.echo(f"📥  Importing {input_file} into corpus {corpus_id}")

    batch_size = 100
    processed = 0
    skipped = 0
    errors = 0

    try:
        with open(input_file) as f:
            content = f.read().strip()

        if not content:
            click.echo("⚠️  Input file is empty")
            return

        if content.startswith("["):
            json_str = content
            if json_str.endswith(","):
                json_str = json_str[:-1] + "]"
            try:
                docs = json.loads(json_str)
            except json.JSONDecodeError as e:
                click.echo(f"❌  Invalid JSON: {e}", err=True)
                sys.exit(1)
        else:
            lines = content.split("\n")
            docs = []
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                try:
                    docs.append(json.loads(line))
                except json.JSONDecodeError as e:
                    click.echo(f"⚠️  Skipping invalid line: {e}", err=True)
                    errors += 1

        total = len(docs)
        click.echo(f"   Found {total} documents to import")

        for i in range(0, total, batch_size):
            batch = docs[i : i + batch_size]
            payload = {
                "documents": batch,
                "corpus_id": corpus_id,
                "skip_duplicates": skip_duplicates,
            }
            try:
                with httpx.Client(timeout=60) as client:
                    r = client.post(f"{api_url}/documents/import", json=payload, headers=headers)
                    if r.status_code == 200:
                        result = r.json()
                        processed += len(batch)
                        skipped += result.get("skipped", 0)
                    else:
                        errors += len(batch)
            except httpx.RequestError as e:
                click.echo(f"⚠️  Batch {i // batch_size + 1} failed: {e}", err=True)
                errors += len(batch)

            if (i + batch_size) % 1000 == 0 or i + batch_size >= total:
                click.echo(f"   Processed {min(i + batch_size, total)}/{total} documents")

    except Exception as e:
        click.echo(f"❌  Import failed: {e}", err=True)
        sys.exit(1)

    click.echo(f"✅  Import complete: {processed} processed, {skipped} skipped, {errors} errors")


# ── Helpers ───────────────────────────────────────────────────────────────────


async def _init_db(dsn: str) -> None:
    """Create or update DB schema using PostgresClient.init_schema."""
    try:
        from dewie.storage.postgres import PostgresClient  # noqa: PLC0415

        pg = PostgresClient(dsn=dsn)
        await pg.init_schema()
        await pg.close()
        click.echo("✅  DB schema initialized.")
    except Exception as exc:
        raise click.ClickException(f"Database initialization failed: {exc}") from exc


def _bridge_dewie_yml_to_env(config_dir: str) -> None:
    """Load dewie.yml and push key values into os.environ if not already set.

    The app reads POSTGRES_DSN, ADMIN_KEY, JWT_SECRET, and INTERNAL_SERVICE_KEY
    directly from os.environ, so they must be wired here before uvicorn launches.
    """
    config_path = os.path.join(config_dir, "dewie.yml")
    yml: dict = {}
    if os.path.exists(config_path):
        try:
            import yaml  # noqa: PLC0415
            with open(config_path) as f:
                yml = yaml.safe_load(f) or {}
        except Exception:
            pass

    # DB — prefer new field name, fall back to old one
    discrete_postgres_env = any(
        os.environ.get(var)
        for var in ("POSTGRES_HOST", "POSTGRES_PORT", "POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_DB")
    )
    if not os.environ.get("POSTGRES_DSN") and not discrete_postgres_env:
        db = yml.get("postgres_dsn") or yml.get("dewie_db")
        if db:
            os.environ["POSTGRES_DSN"] = str(db).strip()
        else:
            os.environ["POSTGRES_DSN"] = f"sqlite+aiosqlite:///{os.path.abspath('dewie.db')}"

    # Secrets — only set if not already in environment
    for env_var, yml_key in (
        ("ADMIN_KEY",             "admin_key"),
        ("JWT_SECRET",            "jwt_secret"),
        ("INTERNAL_SERVICE_KEY",  "internal_service_key"),
    ):
        if not os.environ.get(env_var) and yml.get(yml_key):
            os.environ[env_var] = str(yml[yml_key]).strip()


def _read_db_from_dewie_yml(config_dir: str) -> str | None:
    """Read postgres_dsn from dewie.yml when available.

    Supports both old dewie_db field and new postgres_dsn field for backward compatibility.
    Priority: postgres_dsn > dewie_db
    """
    config_path = os.path.join(config_dir, "dewie.yml")
    if not os.path.exists(config_path):
        return None

    try:
        import yaml  # noqa: PLC0415

        with open(config_path) as f:
            data = yaml.safe_load(f) or {}

        # Try new field first (postgres_dsn), then fallback to old field (dewie_db)
        db = data.get("postgres_dsn") or data.get("dewie_db")
        return str(db).strip() if db else None
    except Exception:
        return None


_MISSING = object()


def _config_path(config_dir: str) -> Path:
    return Path(config_dir) / "dewie.yml"


def _load_config(path: Path) -> dict[str, Any]:
    _require("yaml", "pip install pyyaml")
    import yaml  # noqa: PLC0415

    if not path.exists():
        return {}
    loaded = yaml.safe_load(path.read_text())
    return loaded if isinstance(loaded, dict) else {}


def _save_config(path: Path, data: dict[str, Any]) -> None:
    _require("yaml", "pip install pyyaml")
    import yaml  # noqa: PLC0415

    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(yaml.safe_dump(data, sort_keys=True), encoding="utf-8")
    tmp.replace(path)


def _get_nested(data: dict[str, Any], dotted_path: str) -> Any:
    cur: Any = data
    for part in dotted_path.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return _MISSING
        cur = cur[part]
    return cur


def _set_nested(data: dict[str, Any], dotted_path: str, value: Any) -> None:
    parts = dotted_path.split(".")
    cur: dict[str, Any] = data
    for part in parts[:-1]:
        nxt = cur.get(part)
        if not isinstance(nxt, dict):
            nxt = {}
            cur[part] = nxt
        cur = nxt
    cur[parts[-1]] = value


def _coerce_config_value(raw: str, value_type: str) -> Any:
    value_type = value_type.lower()
    if value_type == "str":
        return raw
    if value_type == "int":
        return int(raw)
    if value_type == "float":
        return float(raw)
    if value_type == "bool":
        norm = raw.strip().lower()
        if norm in {"1", "true", "yes", "on"}:
            return True
        if norm in {"0", "false", "no", "off"}:
            return False
        raise click.ClickException(f"Invalid bool value: {raw}")
    if value_type == "json":
        return json.loads(raw)

    norm = raw.strip().lower()
    if norm in {"true", "false"}:
        return norm == "true"
    try:
        return int(raw)
    except ValueError:
        pass
    try:
        return float(raw)
    except ValueError:
        pass
    if raw.startswith("{") or raw.startswith("["):
        try:
            return json.loads(raw)
        except Exception:
            return raw
    return raw


def _import_env_file(path: Path, data: dict[str, Any]) -> int:
    if not path.exists():
        raise click.ClickException(f"Env file not found: {path}")

    mapping = {
        "POSTGRES_DSN": "postgres_dsn",
        "DEWIE_DB": "postgres_dsn",  # Map old DEWIE_DB env var to postgres_dsn for backward compat
        "REDIS_URL": "redis_url",
        "AUTH_ENABLED": "auth_enabled",
        "QUERY_DEFAULT_RANKER": "query_default_ranker",
        "CHAT_SERVER_AQ": "chat_server_aq",
        "CHAT_MODEL_AQ": "chat_model_aq",
        "CHAT_SERVER_KE": "chat_server_ke",
        "CHAT_MODEL_KE": "chat_model_ke",
        "EMBED_SERVER": "embed_server",
        "EMBED_MODEL": "embed_model",
        "ENRICHMENT_MODEL": "enrichment_model",
        "EMBEDDING_MODEL": "embedding_model",
    }

    imported = 0
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        target = mapping.get(key)
        if not target:
            continue
        _set_nested(data, target, _coerce_config_value(value, "auto"))
        imported += 1
    return imported


@main.command("install")
@click.argument("harness", type=click.Choice(["openclaw"]))
@click.option("--api-url", default="http://localhost:10946", show_default=True, help="Dewie API URL reachable from the harness.")
@click.option("--db-url", default=None, envvar="POSTGRES_DSN", help="Database URL (or set POSTGRES_DSN). If not set, uses dewie.yml.")
@click.option("--workspace-dir", default=None, help="OpenClaw workspace dir (default: ~/.openclaw/workspace).")
@click.option("--key-name", default="dewie-install", show_default=True, help="Label stored on the created API key.")
@click.option("--force", is_flag=True, default=False, help="Overwrite an existing skill file that differs from the canonical one.")
@click.option("--dry-run", is_flag=True, default=False, help="Print what would happen without writing anything.")
def install(
    harness: str,
    api_url: str,
    db_url: str | None,
    workspace_dir: str | None,
    key_name: str,
    force: bool,
    dry_run: bool,
) -> None:
    """Set up Dewie as an MCP server for a coding-agent harness."""
    from dewie import install_openclaw as inst

    if not db_url:
        db_url = _read_db_from_dewie_yml(".")
    if not db_url:
        db_url = "postgresql+asyncpg://dewie:dewie@localhost:5432/dewie"  # Dev-only default — do not use in production

    workspace = Path(workspace_dir) if workspace_dir else inst.default_workspace_dir()

    try:
        if dry_run:
            click.echo("(dry run — no API key created, no files written)")
            click.echo(f"Would register: {inst.register_mcp_server(api_url, '<api-key>', dry_run=True)}")
            click.echo(f"Skill file: {workspace / 'skills' / 'dewie' / 'SKILL.md'} ({inst.write_skill_file(workspace, force=force, dry_run=True)})")
            return

        raw_key = asyncio.run(inst.create_key(db_url, key_name))
        click.echo(f"✅  Created API key: {raw_key}  (shown once — store it now)")

        cmd = inst.register_mcp_server(api_url, raw_key)
        click.echo(f"✅  Registered with OpenClaw: {cmd}")

        skill_result = inst.write_skill_file(workspace, force=force)
        click.echo(f"✅  Skill file {skill_result}: {workspace / 'skills' / 'dewie' / 'SKILL.md'}")

        check = asyncio.run(inst.self_check(api_url, raw_key))
        click.echo(f"✅  Self-check passed: {check}")
    except inst.InstallError as exc:
        raise click.ClickException(str(exc)) from exc


@main.command("admin-user")
@click.option(
    "--username",
    "--email",  # backward-compat alias; email not required
    "username",
    prompt="Admin username",
    help="Username for admin account (email address not required).",
)
@click.option(
    "--password",
    prompt=True,
    hide_input=True,
    confirmation_prompt=True,
    help="Password for admin account (min 8 characters)",
)
@click.option(
    "--db-url",
    default=None,
    envvar="POSTGRES_DSN",
    help="Database URL (or set POSTGRES_DSN env var). If not set, uses dewie.yml or default.",
)
def admin_user(username: str, password: str, db_url: str | None) -> None:
    """Create or update the admin user account. The username does not need to be an email address."""
    # Load DB URL from dewie.yml if not provided
    if not db_url:
        db_url = _read_db_from_dewie_yml(".")
    if not db_url:
        db_url = "postgresql+asyncpg://dewie:dewie@localhost:5432/dewie"  # Dev-only default — do not use in production

    # Validate password
    if len(password) < 8:
        raise click.ClickException("Password must be at least 8 characters")

    # Create/update admin user
    try:
        asyncio.run(_create_or_update_admin(db_url, username, password))
        click.echo(f"✅  Admin user created/updated: {username}")
    except Exception as exc:
        raise click.ClickException(f"Failed to create admin user: {exc}") from exc


async def _create_or_update_admin(db_url: str, username: str, password: str) -> None:
    """Create or update admin user in the database."""
    import uuid

    from sqlalchemy import text

    from dewie.local_auth import hash_password
    from dewie.storage.postgres import PostgresClient

    pg = PostgresClient(dsn=db_url)

    password_hash = hash_password(password)

    async with pg._engine.begin() as conn:
        # Try to update existing user
        result = await conn.execute(
            text(
                "UPDATE users "
                "SET email = :email, password_hash = :hash, is_admin = true "
                "WHERE email = :old_email "
                "RETURNING id"
            ),
            {"email": username, "hash": password_hash, "old_email": username},
        )

        if result.rowcount > 0:
            await pg.close()
            return

        # Create new admin user
        await conn.execute(
            text(
                """
                INSERT INTO users (
                    id, tenant_id, email, name, password_hash,
                    is_admin, plan, activation_status, created_at
                )
                VALUES (
                    :id, :tenant_id, :email, :name, :password_hash,
                    true, 'unlimited', 'approved', now()
                )
                """
            ),
            {
                "id": str(uuid.uuid4()),
                "tenant_id": "00000000-0000-0000-0000-000000000001",
                "email": username,
                "name": "Admin",
                "password_hash": password_hash,
            },
        )

    await pg.close()


if __name__ == "__main__":
    main()
