"""
Unit tests for podcast ingest — Issue #147: Full transcript retention.

Verifies that after transcription and enrichment:
  - body_text in the DB = full transcript text (not replaced by summary)
  - summary is a shorter, derived field generated by the enrichment backend

These tests use mocks for feedparser, whisper, and the DB/enrichment pipeline
so no live services are required.
"""

from __future__ import annotations

import asyncio
from datetime import UTC
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

FULL_TRANSCRIPT = (
    "Welcome to the show. Today we are discussing artificial intelligence and "
    "its impact on society. " * 30  # ~300 words — well above _MIN_WORDS threshold
)

SHORT_SUMMARY = "A discussion of AI and its societal impact."


def _make_episode(title: str = "Test Episode", guid: str = "ep-001") -> dict:  # type: ignore[type-arg]
    """Return a minimal episode dict as produced by fetch_feed."""
    from datetime import datetime

    return {
        "title": title,
        "description": "A test episode.",
        "audio_url": "https://example.com/ep001.mp3",
        "pub_date": datetime(2024, 1, 15, tzinfo=UTC),
        "duration_seconds": 3600,
        "episode_number": 1,
        "season": 1,
        "guid": guid,
    }


# ---------------------------------------------------------------------------
# Test: transcript is stored as body_text, not replaced by summary
# ---------------------------------------------------------------------------


class TestPodcastTranscriptRetention:
    """Verify the full transcript is stored in body_text after ingest."""

    def test_ingest_stores_full_transcript_as_body_text(self):
        """
        The transcript from Whisper must land in the body_text DB column.
        It must NOT be replaced by the enrichment summary.
        """
        written_rows = []

        # Simulate a psycopg2 cursor/connection that captures INSERT params
        mock_cur = MagicMock()

        def fake_execute(sql, params):
            if "INSERT INTO documents" in sql:
                # params = (doc_url, title, body_text, source, corpus_id, published_at)
                written_rows.append(params)

        mock_cur.execute.side_effect = fake_execute
        mock_cur.__enter__ = lambda self: self
        mock_cur.__exit__ = MagicMock(return_value=False)

        mock_conn = MagicMock()
        mock_conn.cursor.return_value = mock_cur
        mock_conn.commit = MagicMock()

        with (
            patch("dewie.ingestion.podcast.fetch_feed", return_value=[_make_episode()]),
            patch("dewie.ingestion.podcast.transcribe_episode", return_value=FULL_TRANSCRIPT),
        ):
            from dewie.ingestion.podcast import ingest_podcast_feed

            results = asyncio.run(
                ingest_podcast_feed(
                    feed_url="https://feeds.example.com/podcast.rss",
                    pg=mock_conn,
                    limit=1,
                    model_size="base",
                    dry_run=False,
                )
            )

        # One episode should be ingested
        assert len(results) == 1
        assert results[0]["status"] == "ingested"

        # The INSERT was called
        assert len(written_rows) == 1, "Expected exactly one INSERT"
        inserted_params = written_rows[0]

        # body_text is the 3rd positional param in the INSERT:
        # (doc_url, title, body_text, source, corpus_id, published_at)
        body_text_in_db = inserted_params[2]

        assert body_text_in_db == FULL_TRANSCRIPT, (
            "body_text in DB must equal the full transcript, not a summary"
        )
        assert len(body_text_in_db) > len(SHORT_SUMMARY), (
            "body_text must be longer than any derived summary"
        )

    def test_ingest_word_count_matches_transcript(self):
        """
        The result's word count must reflect the full transcript, not a truncated version.
        """
        word_count_in_result = None

        mock_cur = MagicMock()
        mock_cur.__enter__ = lambda self: self
        mock_cur.__exit__ = MagicMock(return_value=False)
        mock_conn = MagicMock()
        mock_conn.cursor.return_value = mock_cur

        with (
            patch("dewie.ingestion.podcast.fetch_feed", return_value=[_make_episode()]),
            patch("dewie.ingestion.podcast.transcribe_episode", return_value=FULL_TRANSCRIPT),
        ):
            from dewie.ingestion.podcast import ingest_podcast_feed

            results = asyncio.run(
                ingest_podcast_feed(
                    feed_url="https://feeds.example.com/podcast.rss",
                    pg=mock_conn,
                    limit=1,
                    dry_run=False,
                )
            )

        word_count_in_result = results[0]["words"]
        expected_words = len(FULL_TRANSCRIPT.split())
        assert word_count_in_result == expected_words


class TestPodcastEnrichmentSummaryIsShorter:
    """
    After enrichment, summary must be shorter than body_text.
    The enrichment pipeline must not replace body_text with summary.
    """

    @pytest.mark.asyncio
    async def test_apply_result_does_not_overwrite_body(self):
        """
        _apply_result_to_doc sets doc.summary but must never touch doc.body.
        body is the in-memory transcript; summary is the LLM-derived short form.
        """
        from dewie.enrichment.base import ExtractionResult
        from dewie.enrichment.processor import _apply_result_to_doc
        from dewie.models.content import ContentDocument

        doc = ContentDocument(
            url="podcast:example.com:ep:001",
            title="Test Episode",
            body=FULL_TRANSCRIPT,
            summary="",
        )
        result = ExtractionResult(
            summary=SHORT_SUMMARY,
            keywords=["AI", "society"],
            themes=["technology"],
            entities=[],
            document_type="podcast",
        )

        _apply_result_to_doc(doc, result)

        # summary is now the short LLM summary
        assert doc.summary == SHORT_SUMMARY
        # body is untouched — still the full transcript
        assert doc.body == FULL_TRANSCRIPT
        # summary is shorter than body
        assert len(doc.summary) < len(doc.body)

    @pytest.mark.asyncio
    async def test_enrichment_summary_derived_from_body(self):
        """
        The enrichment backend receives body_text as context; the resulting summary
        must be shorter. This is the contract: summary != body_text.
        """
        from dewie.enrichment.processor import MetadataProcessor
        from dewie.models.content import ContentDocument, ContentStatus

        doc = ContentDocument(
            url="podcast:example.com:ep:002",
            title="Episode 2",
            body=FULL_TRANSCRIPT,
        )

        # Mock a backend that returns a short summary
        mock_backend = AsyncMock()
        import json

        mock_backend.name = "mock"
        mock_backend.complete.return_value = json.dumps(
            {
                "summary": SHORT_SUMMARY,
                "embed_summary": SHORT_SUMMARY,
                "keywords": ["AI"],
                "themes": ["technology"],
                "entities": [],
                "document_type": "podcast",
                "sentiment": 0.5,
                "tone": "neutral",
                "reading_level": "standard",
                "author": "",
                "language": "en",
                "answers_questions": [],
                "enrichment_quality_score": 0.9,
            }
        )

        mock_router = MagicMock()
        mock_router.select.return_value = mock_backend

        mock_registry = MagicMock()

        processor = MetadataProcessor(
            router=mock_router,
            registry=mock_registry,
            max_retries=1,
        )

        enriched = await processor.enrich(doc)

        # Status should be READY
        assert enriched.status == ContentStatus.READY

        # Summary is the short LLM output
        assert enriched.summary == SHORT_SUMMARY

        # body is still the full transcript (in-memory; not replaced by summary)
        assert enriched.body == FULL_TRANSCRIPT

        # Summary must be shorter than the full transcript
        assert len(enriched.summary) < len(enriched.body), (
            "summary must be a shorter derived field, not the full transcript"
        )


class TestPodcastFallback:
    """Verify fallback to metadata only when Whisper is unavailable."""

    def test_ingest_falls_back_on_import_error(self):
        """
        If transcribe_episode raises ImportError, the episode should still
        be ingested with empty body_text (fallback mode).
        """
        written_rows = []
        mock_cur = MagicMock()
        def fake_execute(sql, params):
            if "INSERT INTO documents" in sql:
                written_rows.append(params)
        mock_cur.execute.side_effect = fake_execute
        mock_cur.__enter__ = lambda self: self
        mock_cur.__exit__ = MagicMock(return_value=False)
        mock_conn = MagicMock()
        mock_conn.cursor.return_value = mock_cur
        mock_conn.commit = MagicMock()

        with (
            patch("dewie.ingestion.podcast.fetch_feed", return_value=[_make_episode()]),
            patch("dewie.ingestion.podcast.transcribe_episode", side_effect=ImportError("No Whisper backend found")),
        ):
            from dewie.ingestion.podcast import ingest_podcast_feed

            results = asyncio.run(
                ingest_podcast_feed(
                    feed_url="https://feeds.example.com/podcast.rss",
                    pg=mock_conn,
                    limit=1,
                    dry_run=False,
                )
            )

        # One episode should be ingested
        assert len(results) == 1
        assert results[0]["status"] == "ingested"
        assert results[0]["words"] == 0

        # The INSERT was called with empty body_text
        assert len(written_rows) == 1
        inserted_params = written_rows[0]
        body_text_in_db = inserted_params[2]
        assert body_text_in_db == ""
